/*
Retrieves the top 10 highest-paying remote Data Analyst jobs
along with the specific skills required for each role.
*/

-- Create a CTE for the top 10 highest-paying jobs
WITH top_paying_jobs AS(
    SELECT
        job_id,
        job_title,
        job_country,
        name AS company_name,
        salary_year_avg
    FROM job_postings_fact
    LEFT JOIN company_dim ON company_dim.company_id = job_postings_fact.company_id
    WHERE
        job_title_short = 'Data Analyst' AND
        salary_year_avg IS NOT NULL AND
        job_location = 'Anywhere'
    ORDER BY salary_year_avg DESC
    LIMIT 10
)

SELECT 
    top_paying_jobs.*,
    skills_dim.skills
FROM top_paying_jobs
INNER JOIN skills_job_dim on skills_job_dim.job_id = top_paying_jobs.job_id
INNER JOIN skills_dim on skills_dim.skill_id  = skills_job_dim.skill_id


/*  
Skills analysis based on insights generated by ChatGPT:
    SQL and Python are the most in-demand skills, appearing in the majority of top-paying positions.
    Data visualization tools such as Tableau and Power BI are highly valued, highlighting the importance of data storytelling.
    Cloud and data platform skills (Azure, AWS, Snowflake, Databricks) indicate strong demand for modern data infrastructure knowledge.
    Traditional tools like Excel remain relevant, even in high-paying roles.
    Collaboration and DevOps-related tools (Git, Jira, Confluence, Bitbucket) suggest analysts are expected to work closely with engineering teams.
    Big data and advanced analytics tools (PySpark, Hadoop, Pandas, NumPy) appear less frequently but are associated with specialized, high-paying roles.
*/



